sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  # I'd like to do this without "-e", but then pip barfs:
  # https://github.com/pypa/pip/issues/1236
  - pip install -e .[testing]
script: nosetests
